//
//  PreviewViewController.swift
//  nextap
//
//  Created by Tomáš Černý on 14/09/2020.
//  Copyright (c) 2020 Tomáš Černý. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import OHCubeView
import AlamofireImage

final class PreviewViewController: UIViewController {

    @IBOutlet weak var cubeView: OHCubeView!
    // MARK: - Public properties -

    var presenter: PreviewPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        //self.cubeView.delegate = self
        self.cubeView.cubeDelegate = self
        presenter.viewDidLoad()
    }
    
    
}

// MARK: - Extensions -

extension PreviewViewController: PreviewViewInterface {
    func addStoryView(view: StoryView) {
        self.cubeView.addChildView(view)
    }
    
    func getFrame() -> CGRect {
        return self.view.frame
    }
    
    func scrollToImage(at index: IndexPath) {
        self.view.layoutIfNeeded()
        self.cubeView.scrollToViewAtIndex(index.row, animated: false)
    }
    
}

extension PreviewViewController: OHCubeViewDelegate {
    
    func cubeViewDidEndDecelerating(_ cubeView: OHCubeView) {
        let index = Int(cubeView.contentOffset.x / cubeView.bounds.size.width)
        presenter.previewIndexChanged(to: index)
    }
}
