//
//  PreviewInteractor.swift
//  nextap
//
//  Created by Tomáš Černý on 14/09/2020.
//  Copyright (c) 2020 Tomáš Černý. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PreviewInteractor {
}

// MARK: - Extensions -

extension PreviewInteractor: PreviewInteractorInterface {
}
