//
//  PreviewInterfaces.swift
//  nextap
//
//  Created by Tomáš Černý on 14/09/2020.
//  Copyright (c) 2020 Tomáš Černý. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PreviewWireframeInterface: WireframeInterface {
    func dismissButtonTouched(at: IndexPath)
}

protocol PreviewViewInterface: ViewInterface {
    func getFrame() -> CGRect
    func addStoryView(view : StoryView)
    func scrollToImage(at index: IndexPath)
}

protocol PreviewPresenterInterface: PresenterInterface {
    func dismissButtonTouched()
    func getItem(at: Int) -> Story
}

protocol PreviewInteractorInterface: InteractorInterface {
}
