//
//  PreviewWireframe.swift
//  nextap
//
//  Created by Tomáš Černý on 14/09/2020.
//  Copyright (c) 2020 Tomáš Černý. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PreviewWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Preview", bundle: nil)

    // MARK: - Module setup -

    init(indexPath: IndexPath, withStories stories: [Story], previewDelegate: PreviewDelegate) {
        let moduleViewController = storyboard.instantiateViewController(ofType: PreviewViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = PreviewInteractor()
        let presenter = PreviewPresenter(view: moduleViewController, interactor: interactor, wireframe: self, indexPath: indexPath, stories: stories)
        moduleViewController.presenter = presenter
        presenter.delegate = previewDelegate
    }

}

// MARK: - Extensions -

extension PreviewWireframe: PreviewWireframeInterface {
    func dismissButtonTouched() {
        navigationController?.popViewController(animated: true)
    }
    
}
