//
//  FeedWireframe.swift
//  nextap
//
//  Created by Tomáš Černý on 14/09/2020.
//  Copyright (c) 2020 Tomáš Černý. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeedWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Feed", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: FeedViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = FeedInteractor()
        let presenter = FeedPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension FeedWireframe: FeedWireframeInterface {
    
    func openDetail(at indexPath: IndexPath, withStories stories: [Story], previewDelegate: PreviewDelegate) {
        //prepopulating detailsView with all the stories, as the endpoint is the same
        navigationController?.pushWireframe(PreviewWireframe(indexPath: indexPath, withStories: stories, previewDelegate: previewDelegate))
    }
    
}
