//
//  FeedInterfaces.swift
//  nextap
//
//  Created by Tomáš Černý on 14/09/2020.
//  Copyright (c) 2020 Tomáš Černý. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

protocol FeedWireframeInterface: WireframeInterface {
    func openDetail(at indexPath: IndexPath, withStories stories: [Story], previewDelegate: PreviewDelegate)
}

protocol FeedViewInterface: ViewInterface {
    func reloadData()
    func scrollToIndex(indexPath: IndexPath)
}

protocol FeedPresenterInterface: PresenterInterface {
    func numberOfSections() -> Int
    func numberOfItems(in section: Int) -> Int
    func item(at indexPath: IndexPath) -> Story
    func didSelectItem(at indexPath: IndexPath)
}

protocol FeedInteractorInterface: InteractorInterface {
    func fetchStories(_ completion: @escaping (DataResponse<FeedResult, AFError>) -> (Void))
}
